
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows
 */
public class Atividade extends javax.swing.JFrame {

    Integer CPUmin = 0;
           Integer cpumed = 0;
           Integer cpumax = 0;
           Integer cputotal = 0;
           Integer botao = 0;
           
           Random aleat = new Random();
           
           Integer memototal = 0;  
           Integer disctotal = 0;
           Integer qtdtotal = 0;
           Integer cpuvmed = 0;        
           Integer memovmed = 0;
           Integer memovmax = 0;
           Integer memovmin = 0;
           Integer discvmed = 0;  
           Integer discvmax = 0; 
           Integer discvmin = 0; 
           Integer cpuvmin = 0; 
           Integer cpuvmax = 0; 
          
    /**
     * Creates new form Atividade
     */
    public Atividade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        barcpu = new javax.swing.JProgressBar();
        barmem = new javax.swing.JProgressBar();
        bardisc = new javax.swing.JProgressBar();
        lblcpu = new javax.swing.JLabel();
        lblmemo = new javax.swing.JLabel();
        lbldisc = new javax.swing.JLabel();
        lblmincpu = new javax.swing.JLabel();
        lblcpuvmin = new javax.swing.JLabel();
        lblcpumed = new javax.swing.JLabel();
        lblcpuvmed = new javax.swing.JLabel();
        lblcpumax = new javax.swing.JLabel();
        lblcpuvmax = new javax.swing.JLabel();
        lblmemmin = new javax.swing.JLabel();
        lblmemvmin = new javax.swing.JLabel();
        lblmemmed = new javax.swing.JLabel();
        lblmemvmed = new javax.swing.JLabel();
        lblmemmax = new javax.swing.JLabel();
        lblmemvmax = new javax.swing.JLabel();
        lbldiscmin = new javax.swing.JLabel();
        lbldiscvmin = new javax.swing.JLabel();
        lbldiscmed = new javax.swing.JLabel();
        lbldiscvmed = new javax.swing.JLabel();
        lbldiscmax = new javax.swing.JLabel();
        lbldiscvmax = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        btn1.setForeground(new java.awt.Color(0, 102, 102));
        btn1.setText("Calcular");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        lblcpu.setText("CPU");

        lblmemo.setText("Memória");

        lbldisc.setText("Disco");

        lblmincpu.setText("Min:");

        lblcpumed.setText("Médio:");

        lblcpumax.setText("Max:");

        lblmemmin.setText("Min:");

        lblmemmed.setText("Médio:");

        lblmemmax.setText("Max:");

        lbldiscmin.setText("Min:");

        lbldiscmed.setText("Médio:");

        lbldiscmax.setText("Max:");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Informações sobre a máquina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bardisc, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barmem, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmemo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblmemmin)
                                .addGap(50, 50, 50)
                                .addComponent(lblmemvmin)
                                .addGap(40, 40, 40)
                                .addComponent(lblmemmed)
                                .addGap(50, 50, 50)
                                .addComponent(lblmemvmed)
                                .addGap(40, 40, 40)
                                .addComponent(lblmemmax)
                                .addGap(50, 50, 50)
                                .addComponent(lblmemvmax)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btn1)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblcpu)
                                .addComponent(lbldisc)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblmincpu)
                                    .addGap(50, 50, 50)
                                    .addComponent(lblcpuvmin)
                                    .addGap(40, 40, 40)
                                    .addComponent(lblcpumed)
                                    .addGap(50, 50, 50)
                                    .addComponent(lblcpuvmed)
                                    .addGap(40, 40, 40)
                                    .addComponent(lblcpumax)
                                    .addGap(50, 50, 50)
                                    .addComponent(lblcpuvmax))
                                .addComponent(barcpu, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbldiscmin)
                                    .addGap(50, 50, 50)
                                    .addComponent(lbldiscvmin)
                                    .addGap(40, 40, 40)
                                    .addComponent(lbldiscmed)
                                    .addGap(50, 50, 50)
                                    .addComponent(lbldiscvmed)
                                    .addGap(40, 40, 40)
                                    .addComponent(lbldiscmax)
                                    .addGap(50, 50, 50)
                                    .addComponent(lbldiscvmax))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcpu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barcpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmincpu)
                    .addComponent(lblcpuvmin)
                    .addComponent(lblcpumed)
                    .addComponent(lblcpuvmed)
                    .addComponent(lblcpumax)
                    .addComponent(lblcpuvmax))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblmemo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barmem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmemmin)
                            .addComponent(lblmemvmin)
                            .addComponent(lblmemmed)
                            .addComponent(lblmemvmed)
                            .addComponent(lblmemmax)
                            .addComponent(lblmemvmax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addComponent(lbldisc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bardisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldiscmin)
                    .addComponent(lbldiscvmin)
                    .addComponent(lbldiscmed)
                    .addComponent(lbldiscvmed)
                    .addComponent(lbldiscmax)
                    .addComponent(lbldiscvmax))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       Integer cpu = aleat.nextInt(100);
           Integer memo = aleat.nextInt(100);
           Integer disc = aleat.nextInt(100);
               
                   
           cputotal = cputotal + cpu;
           memototal = memototal + memo;
           disctotal = disctotal + disc;
           
           qtdtotal = qtdtotal + 1;
           
           cpuvmed = cputotal / qtdtotal;
           memovmed = memototal / qtdtotal;
           discvmed = disctotal / qtdtotal;
           
           if(cpu < cpuvmin || cpuvmin == 0){
               cpuvmin = cpu;
           }
           
           if(cpu > cpuvmax){
               cpuvmax = cpu;
           }
           
            if(memo < memovmin || memovmin == 0){
               memovmin = memo;
           }
           
           if(memo > memovmax){
               memovmax = memo;
           }
           
            if(disc < discvmin || discvmin == 0){
               discvmin = disc;
           }
           
           if(disc > discvmax){
               discvmax = disc;
           }
           
           barcpu.setStringPainted(true);
           barcpu.setMinimum(0);
           barcpu.setMaximum(100);
           barcpu.setValue(cpu);
           barcpu.setString(String.format("%d%%", cpu));
           
           bardisc.setStringPainted(true);
           bardisc.setMinimum(0);
           bardisc.setMaximum(100);
           bardisc.setValue(disc);
           bardisc.setString(String.format("%d%%", disc));
           
           barmem.setStringPainted(true);
           barmem.setMinimum(0);
           barmem.setMaximum(100);
           barmem.setValue(memo);
           barmem.setString(String.format("%d%%", memo));
           
           lblcpuvmin.setText(String.format("%d%%", cpuvmin));
           lblcpuvmax.setText(String.format("%d%%", cpuvmax));
           lblcpuvmed.setText(String.format("%d%%", cpuvmed));
           
           lbldiscvmin.setText(String.format("%d%%", discvmin));
           lbldiscvmax.setText(String.format("%d%%", discvmax));
           lbldiscvmed.setText(String.format("%d%%", discvmed));  

           lblmemvmin.setText(String.format("%d%%", memovmin));
           lblmemvmax.setText(String.format("%d%%", memovmax));
           lblmemvmed.setText(String.format("%d%%", memovmed));
// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
           
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barcpu;
    private javax.swing.JProgressBar bardisc;
    private javax.swing.JProgressBar barmem;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcpu;
    private javax.swing.JLabel lblcpumax;
    private javax.swing.JLabel lblcpumed;
    private javax.swing.JLabel lblcpuvmax;
    private javax.swing.JLabel lblcpuvmed;
    private javax.swing.JLabel lblcpuvmin;
    private javax.swing.JLabel lbldisc;
    private javax.swing.JLabel lbldiscmax;
    private javax.swing.JLabel lbldiscmed;
    private javax.swing.JLabel lbldiscmin;
    private javax.swing.JLabel lbldiscvmax;
    private javax.swing.JLabel lbldiscvmed;
    private javax.swing.JLabel lbldiscvmin;
    private javax.swing.JLabel lblmemmax;
    private javax.swing.JLabel lblmemmed;
    private javax.swing.JLabel lblmemmin;
    private javax.swing.JLabel lblmemo;
    private javax.swing.JLabel lblmemvmax;
    private javax.swing.JLabel lblmemvmed;
    private javax.swing.JLabel lblmemvmin;
    private javax.swing.JLabel lblmincpu;
    // End of variables declaration//GEN-END:variables
}
